# Generated by Django 5.2.13 on 2026-06-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_affiliate_affiliatewallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateTokenBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_jti', models.CharField(max_length=255, unique=True)),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'affiliate_token_blacklist',
            },
        ),
    ]
