# Generated by Django 5.2.13 on 2026-06-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_affiliatetokenblacklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_auto_approve', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'System Settings',
            },
        ),
    ]
