# Generated by Django 5.2.13 on 2026-06-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_systemsettings_min_withdrawal_tracking_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='transfer_fee',
            field=models.IntegerField(default=10000),
        ),
    ]
