# Generated by Django 5.2.13 on 2026-06-04 17:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_affiliatetokenblacklist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('commission_type', models.CharField(choices=[('flat_fee', 'Flat Fee'), ('percentage', 'Percentage'), ('percentage_capped', 'Percentage Capped')], max_length=24)),
                ('commission_value', models.IntegerField()),
                ('commission_cap', models.IntegerField(blank=True, null=True)),
                ('tier', models.CharField(blank=True, max_length=32, null=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('conversion_limit', models.IntegerField(blank=True, null=True)),
                ('terms_and_conditions', models.TextField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, db_column='cancelled_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_campaigns', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignAffiliate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='campaign_affiliates', to='accounts.affiliate')),
                ('assigned_by', models.ForeignKey(db_column='assigned_by', on_delete=django.db.models.deletion.PROTECT, related_name='assigned_campaign_affiliates', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='campaign_affiliates', to='campaigns.campaign')),
                ('removed_by', models.ForeignKey(blank=True, db_column='removed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removed_campaign_affiliates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'campaign_affiliates',
                'unique_together': {('campaign', 'affiliate')},
            },
        ),
    ]
