# Generated by Django 5.2.13 on 2026-06-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='commission_per_tier',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='commission_period_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='commission_trigger',
            field=models.CharField(blank=True, choices=[('first_subscription_only', 'First Subscription Only'), ('all_subscriptions', 'All Subscriptions'), ('subscriptions_within_period', 'Subscriptions Within Period')], max_length=32, null=True),
        ),
    ]
