# Generated by Django 5.2.13 on 2026-06-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_commission_per_tier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='commission_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
