# Generated by Django 5.2.13 on 2026-06-04 18:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_affiliatetokenblacklist'),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('use_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='codes', to='accounts.affiliate')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='codes', to='campaigns.campaign')),
                ('campaign_affiliate', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='code', to='campaigns.campaignaffiliate')),
            ],
            options={
                'db_table': 'affiliate_codes',
            },
        ),
        migrations.CreateModel(
            name='AffiliateLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=32, unique=True)),
                ('full_url', models.CharField(max_length=512)),
                ('click_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='links', to='accounts.affiliate')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='links', to='campaigns.campaign')),
                ('campaign_affiliate', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='link', to='campaigns.campaignaffiliate')),
            ],
            options={
                'db_table': 'affiliate_links',
            },
        ),
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attribution_source', models.CharField(choices=[('coupon_code', 'Coupon Code'), ('tracking_link', 'Tracking Link'), ('unattributed', 'Unattributed')], max_length=16)),
                ('merchant_subscription_id', models.CharField(max_length=128)),
                ('merchant_id', models.CharField(max_length=128)),
                ('merchant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_at', models.DateTimeField()),
                ('is_self_referral', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='conversions', to='accounts.affiliate')),
                ('affiliate_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='tracking.affiliatecode')),
                ('affiliate_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='tracking.affiliatelink')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='conversions', to='campaigns.campaign')),
            ],
            options={
                'db_table': 'conversions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('earned', 'Earned'), ('reversed', 'Reversed'), ('pending', 'Pending')], default='earned', max_length=16)),
                ('amount', models.IntegerField()),
                ('payment_amount', models.IntegerField()),
                ('commission_type_snapshot', models.CharField(max_length=24)),
                ('commission_value_snapshot', models.IntegerField()),
                ('commission_cap_snapshot', models.IntegerField(blank=True, null=True)),
                ('external_payment_id', models.CharField(blank=True, max_length=128, null=True)),
                ('earned_at', models.DateTimeField()),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='commissions', to='accounts.affiliate')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='commissions', to='campaigns.campaign')),
                ('reversed_commission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='tracking.commission')),
                ('conversion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='commissions', to='tracking.conversion')),
            ],
            options={
                'db_table': 'commissions',
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='LinkClick',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clicked_at', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('referrer_url', models.TextField(blank=True, null=True)),
                ('session_fingerprint', models.CharField(blank=True, max_length=128, null=True)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='clicks', to='accounts.affiliate')),
                ('affiliate_link', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='clicks', to='tracking.affiliatelink')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='clicks', to='campaigns.campaign')),
                ('conversion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks', to='tracking.conversion')),
            ],
            options={
                'db_table': 'link_clicks',
                'ordering': ['-clicked_at'],
            },
        ),
    ]
