# Generated by Django 5.2.13 on 2026-06-05 23:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_affiliatetokenblacklist'),
        ('campaigns', '0001_initial'),
        ('tracking', '0002_centralwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MerchantLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merchant_id', models.CharField(max_length=128, unique=True)),
                ('merchant_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('signed_up', 'Signed Up'), ('subscribed', 'Subscribed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='signed_up', max_length=16)),
                ('subscription_tier', models.CharField(blank=True, max_length=32, null=True)),
                ('subscription_start', models.DateTimeField(blank=True, null=True)),
                ('subscription_end', models.DateTimeField(blank=True, null=True)),
                ('amount_paid_kobo', models.IntegerField(blank=True, null=True)),
                ('signed_up_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='accounts.affiliate')),
                ('affiliate_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='tracking.affiliatecode')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='campaigns.campaign')),
            ],
            options={
                'db_table': 'merchant_leads',
                'ordering': ['-signed_up_at'],
            },
        ),
        migrations.AddField(
            model_name='conversion',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='tracking.merchantlead'),
        ),
    ]
