# Generated by Django 5.2.13 on 2026-06-07 14:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_systemsettings'),
        ('payouts', '0001_initial'),
        ('tracking', '0003_conversion_converted_at_merchantlead_conversion_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentralWalletEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('credit', 'Commission Credit'), ('payout', 'Payout Disbursement'), ('reversal', 'Commission Reversal'), ('fee', 'Transfer Fee')], max_length=16)),
                ('amount', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(default='done', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affiliate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_events', to='accounts.affiliate')),
                ('commission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_events', to='tracking.commission')),
                ('payout_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_events', to='payouts.payoutrequest')),
            ],
            options={
                'db_table': 'central_wallet_events',
                'ordering': ['-created_at'],
            },
        ),
    ]
