# Generated by Django 5.2.13 on 2026-06-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0011_merchantofferredemption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantlead',
            name='status',
            field=models.CharField(choices=[('signed_up', 'Signed Up'), ('trial', 'Trial'), ('trial_complete', 'Trial Complete'), ('subscribed', 'Subscribed'), ('renewed', 'Renewed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='trial', max_length=16),
        ),
    ]
